import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notion Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  interCeptedModal,
}: {
  children: React.ReactNode;
  interCeptedModal: React.ReactNode;
}) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      appearance={{
        variables: { colorPrimary: "#000" },
        elements: { footer: "hidden", main: "mb-12" },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          {interCeptedModal}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
