import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ThemeProvider from "@/components/ThemeProvider";
import { clerkProviderConfig } from "@/config/clerk";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Notion Clone",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1a1a" },
  ],
};

export default function RootLayout({
  children,
  auth,
  mobileNav,
}: {
  children: React.ReactNode;
  mobileNav: React.ReactNode;
  auth: React.ReactNode;
}) {
  return (
    <ClerkProvider {...clerkProviderConfig}>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {auth}
            {mobileNav}
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
